//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetApp_Final_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardInformations
    {
        public int CardID { get; set; }
        public string CustomerID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string CreditCardNumber { get; set; }
        public string ExpMonth { get; set; }
        public int ExpYear { get; set; }
        public int CVV { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
