//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetApp_Final_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string DriverID { get; set; }
        public string CustomerID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
